/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vue;

import java.awt.Color;
import java.awt.Component;

/**
 *
 * @author H_Création
 */
public class StudensBanque extends javax.swing.JFrame {

    /**
     * Creates new form StudensBanque
     */
    public StudensBanque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        ButtonAccueil = new javax.swing.JButton();
        ButtonNouveauClient = new javax.swing.JButton();
        ButtonNouveauCompte = new javax.swing.JButton();
        ButtonInfoClient = new javax.swing.JButton();
        ButtonInfCompte = new javax.swing.JButton();
        Buttonoperation = new javax.swing.JButton();
        ButtonListeClient1 = new javax.swing.JButton();
        PannelMain = new javax.swing.JPanel();
        PanrlBienvenue = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PabelAccueill = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Accueil1 = new javax.swing.JLabel();
        Accueil2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        AButtonSolde = new javax.swing.JButton();
        AButtonNouveauCompte = new javax.swing.JButton();
        AButtonInfoClient = new javax.swing.JButton();
        AButtonInfoCompte = new javax.swing.JButton();
        AButtonNouveauClient = new javax.swing.JButton();
        AButtonDepot = new javax.swing.JButton();
        AButtonInfoOperation = new javax.swing.JButton();
        AButtonRetrait = new javax.swing.JButton();
        PanelNouveauClient = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ButtonListeClient = new javax.swing.JButton();
        ButtonListeClient2 = new javax.swing.JButton();
        PanelNouveauCompte = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(252, 116, 34));

        jPanel2.setBackground(new java.awt.Color(0, 24, 72));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Students Banque ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 24, 72));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        ButtonAccueil.setBackground(new java.awt.Color(252, 116, 34));
        ButtonAccueil.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ButtonAccueil.setForeground(new java.awt.Color(255, 255, 255));
        ButtonAccueil.setText("Accueil");
        ButtonAccueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonAccueilMouseClicked(evt);
            }
        });
        ButtonAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAccueilActionPerformed(evt);
            }
        });

        ButtonNouveauClient.setBackground(new java.awt.Color(252, 116, 34));
        ButtonNouveauClient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ButtonNouveauClient.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNouveauClient.setText("Nouveau Client ");
        ButtonNouveauClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNouveauClientActionPerformed(evt);
            }
        });

        ButtonNouveauCompte.setBackground(new java.awt.Color(252, 116, 34));
        ButtonNouveauCompte.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ButtonNouveauCompte.setForeground(new java.awt.Color(255, 255, 255));
        ButtonNouveauCompte.setText("Nouveau compte ");
        ButtonNouveauCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNouveauCompteActionPerformed(evt);
            }
        });

        ButtonInfoClient.setBackground(new java.awt.Color(252, 116, 34));
        ButtonInfoClient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ButtonInfoClient.setForeground(new java.awt.Color(255, 255, 255));
        ButtonInfoClient.setText("Info Client ");
        ButtonInfoClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInfoClientActionPerformed(evt);
            }
        });

        ButtonInfCompte.setBackground(new java.awt.Color(252, 116, 34));
        ButtonInfCompte.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ButtonInfCompte.setForeground(new java.awt.Color(255, 255, 255));
        ButtonInfCompte.setText("Info Compte ");
        ButtonInfCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInfCompteActionPerformed(evt);
            }
        });

        Buttonoperation.setBackground(new java.awt.Color(252, 116, 34));
        Buttonoperation.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Buttonoperation.setForeground(new java.awt.Color(255, 255, 255));
        Buttonoperation.setText("Info Operations ");
        Buttonoperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonoperationActionPerformed(evt);
            }
        });

        ButtonListeClient1.setBackground(new java.awt.Color(252, 116, 34));
        ButtonListeClient1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ButtonListeClient1.setForeground(new java.awt.Color(255, 255, 255));
        ButtonListeClient1.setText("Liste Des Client ");
        ButtonListeClient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListeClient1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonNouveauClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonAccueil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonNouveauCompte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonInfoClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonInfCompte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Buttonoperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonListeClient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(ButtonAccueil, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonNouveauClient, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonNouveauCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonInfoClient, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonInfCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonListeClient1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(Buttonoperation, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PannelMain.setBackground(new java.awt.Color(255, 255, 255));
        PannelMain.setLayout(new java.awt.CardLayout());

        PanrlBienvenue.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(0, 24, 72));
        jLabel2.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 24, 72));
        jButton1.setText("BIENVENUE DANS STUDENTS BANQUE ");

        javax.swing.GroupLayout PanrlBienvenueLayout = new javax.swing.GroupLayout(PanrlBienvenue);
        PanrlBienvenue.setLayout(PanrlBienvenueLayout);
        PanrlBienvenueLayout.setHorizontalGroup(
            PanrlBienvenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanrlBienvenueLayout.setVerticalGroup(
            PanrlBienvenueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanrlBienvenueLayout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel2)
                .addGap(83, 83, 83)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(528, Short.MAX_VALUE))
        );

        PannelMain.add(PanrlBienvenue, "card2");

        PabelAccueill.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 24, 72));

        Accueil1.setBackground(new java.awt.Color(0, 24, 72));
        Accueil1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Accueil1.setForeground(new java.awt.Color(255, 255, 255));
        Accueil1.setText("Connexion");
        Accueil1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Accueil1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Accueil1MouseEntered(evt);
            }
        });

        Accueil2.setBackground(new java.awt.Color(0, 24, 72));
        Accueil2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        Accueil2.setForeground(new java.awt.Color(255, 255, 255));
        Accueil2.setText("Cree Un compte");
        Accueil2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Accueil2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Accueil2MouseEntered(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(252, 116, 34));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(252, 116, 34));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Accueil1)
                .addGap(10, 10, 10)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Accueil2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Accueil1)
                    .addComponent(Accueil2))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 24, 72));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        AButtonSolde.setBackground(new java.awt.Color(204, 204, 255));
        AButtonSolde.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        AButtonSolde.setForeground(new java.awt.Color(0, 24, 72));
        AButtonSolde.setText("Solde ");
        AButtonSolde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AButtonSoldeActionPerformed(evt);
            }
        });

        AButtonNouveauCompte.setBackground(new java.awt.Color(204, 204, 255));
        AButtonNouveauCompte.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        AButtonNouveauCompte.setForeground(new java.awt.Color(0, 24, 72));
        AButtonNouveauCompte.setText("Nouveau compte ");
        AButtonNouveauCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AButtonNouveauCompteActionPerformed(evt);
            }
        });

        AButtonInfoClient.setBackground(new java.awt.Color(204, 204, 255));
        AButtonInfoClient.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        AButtonInfoClient.setForeground(new java.awt.Color(0, 24, 72));
        AButtonInfoClient.setText("Info Client ");
        AButtonInfoClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AButtonInfoClientActionPerformed(evt);
            }
        });

        AButtonInfoCompte.setBackground(new java.awt.Color(204, 204, 255));
        AButtonInfoCompte.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        AButtonInfoCompte.setForeground(new java.awt.Color(0, 24, 72));
        AButtonInfoCompte.setText("Info Compte ");
        AButtonInfoCompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AButtonInfoCompteActionPerformed(evt);
            }
        });

        AButtonNouveauClient.setBackground(new java.awt.Color(204, 204, 255));
        AButtonNouveauClient.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        AButtonNouveauClient.setForeground(new java.awt.Color(0, 24, 72));
        AButtonNouveauClient.setText("Nouveau Client ");
        AButtonNouveauClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AButtonNouveauClientActionPerformed(evt);
            }
        });

        AButtonDepot.setBackground(new java.awt.Color(204, 204, 255));
        AButtonDepot.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        AButtonDepot.setForeground(new java.awt.Color(0, 24, 72));
        AButtonDepot.setText("Dépôt ");
        AButtonDepot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AButtonDepotActionPerformed(evt);
            }
        });

        AButtonInfoOperation.setBackground(new java.awt.Color(204, 204, 255));
        AButtonInfoOperation.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        AButtonInfoOperation.setForeground(new java.awt.Color(0, 24, 72));
        AButtonInfoOperation.setText("Info Operations ");
        AButtonInfoOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AButtonInfoOperationActionPerformed(evt);
            }
        });

        AButtonRetrait.setBackground(new java.awt.Color(204, 204, 255));
        AButtonRetrait.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        AButtonRetrait.setForeground(new java.awt.Color(0, 24, 72));
        AButtonRetrait.setText("Retrait ");
        AButtonRetrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AButtonRetraitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PabelAccueillLayout = new javax.swing.GroupLayout(PabelAccueill);
        PabelAccueill.setLayout(PabelAccueillLayout);
        PabelAccueillLayout.setHorizontalGroup(
            PabelAccueillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PabelAccueillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PabelAccueillLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PabelAccueillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AButtonInfoClient, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AButtonInfoCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AButtonNouveauCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AButtonNouveauClient, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addGroup(PabelAccueillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AButtonSolde, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AButtonDepot, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AButtonInfoOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AButtonRetrait, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131))
        );
        PabelAccueillLayout.setVerticalGroup(
            PabelAccueillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PabelAccueillLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(PabelAccueillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AButtonNouveauClient, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AButtonInfoOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PabelAccueillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AButtonNouveauCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AButtonDepot, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(PabelAccueillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AButtonInfoClient, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AButtonRetrait, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(PabelAccueillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AButtonInfoCompte, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AButtonSolde, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PannelMain.add(PabelAccueill, "card3");

        PanelNouveauClient.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(0, 24, 72));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(252, 116, 34));

        jPanel11.setBackground(new java.awt.Color(252, 116, 34));

        jLabel3.setBackground(new java.awt.Color(252, 116, 34));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 24, 72));
        jLabel3.setText("        NOUVEAU CLIENT");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 102));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 102));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 102));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 0, 102));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(252, 116, 34));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("NOM");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Prenom ");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Date de naissance");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Adresse");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addGap(45, 45, 45)
                .addComponent(jLabel7)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        ButtonListeClient.setBackground(new java.awt.Color(252, 116, 34));
        ButtonListeClient.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ButtonListeClient.setText("VALIDER");
        ButtonListeClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListeClientActionPerformed(evt);
            }
        });

        ButtonListeClient2.setBackground(new java.awt.Color(252, 116, 34));
        ButtonListeClient2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ButtonListeClient2.setText("ANNULER");
        ButtonListeClient2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonListeClient2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(ButtonListeClient, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ButtonListeClient2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))))
                .addGap(39, 39, 39))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ButtonListeClient, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonListeClient2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );

        javax.swing.GroupLayout PanelNouveauClientLayout = new javax.swing.GroupLayout(PanelNouveauClient);
        PanelNouveauClient.setLayout(PanelNouveauClientLayout);
        PanelNouveauClientLayout.setHorizontalGroup(
            PanelNouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNouveauClientLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelNouveauClientLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelNouveauClientLayout.setVerticalGroup(
            PanelNouveauClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNouveauClientLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 456, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PannelMain.add(PanelNouveauClient, "card4");

        PanelNouveauCompte.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(0, 24, 72));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 848, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jButton2.setText("jButton2");

        jButton3.setText("jButton2");

        javax.swing.GroupLayout PanelNouveauCompteLayout = new javax.swing.GroupLayout(PanelNouveauCompte);
        PanelNouveauCompte.setLayout(PanelNouveauCompteLayout);
        PanelNouveauCompteLayout.setHorizontalGroup(
            PanelNouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNouveauCompteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelNouveauCompteLayout.createSequentialGroup()
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(PanelNouveauCompteLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        PanelNouveauCompteLayout.setVerticalGroup(
            PanelNouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNouveauCompteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(PanelNouveauCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 373, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PannelMain.add(PanelNouveauCompte, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PannelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PannelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Accueil1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Accueil1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Accueil1MouseClicked

    private void Accueil1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Accueil1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Accueil1MouseEntered

    private void Accueil2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Accueil2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Accueil2MouseClicked

    private void Accueil2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Accueil2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Accueil2MouseEntered

    private void ButtonListeClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListeClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonListeClientActionPerformed

    private void ButtonInfCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInfCompteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonInfCompteActionPerformed

    private void ButtonInfoClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInfoClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonInfoClientActionPerformed

    private void ButtonNouveauCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNouveauCompteActionPerformed
PannelMain.removeAll();
        PannelMain.repaint();
        PannelMain.revalidate();
        PannelMain.add(PanelNouveauCompte);
        PannelMain.repaint();
        PannelMain.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNouveauCompteActionPerformed

    private void ButtonNouveauClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNouveauClientActionPerformed
PannelMain.removeAll();
        PannelMain.repaint();
        PannelMain.revalidate();
        PannelMain.add(PanelNouveauClient);
        PannelMain.repaint();
        PannelMain.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonNouveauClientActionPerformed

    private void ButtonoperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonoperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonoperationActionPerformed

    private void ButtonAccueilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAccueilMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAccueilMouseClicked

    private void ButtonAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAccueilActionPerformed
        PannelMain.removeAll();
        PannelMain.repaint();
        PannelMain.revalidate();
        PannelMain.add(PabelAccueill);
        PannelMain.repaint();
        PannelMain.revalidate();

        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAccueilActionPerformed

    private void AButtonSoldeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonSoldeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AButtonSoldeActionPerformed

    private void AButtonNouveauCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonNouveauCompteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AButtonNouveauCompteActionPerformed

    private void AButtonInfoClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonInfoClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AButtonInfoClientActionPerformed

    private void AButtonInfoCompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonInfoCompteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AButtonInfoCompteActionPerformed

    private void AButtonNouveauClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonNouveauClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AButtonNouveauClientActionPerformed

    private void AButtonDepotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonDepotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AButtonDepotActionPerformed

    private void AButtonInfoOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonInfoOperationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AButtonInfoOperationActionPerformed

    private void AButtonRetraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AButtonRetraitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AButtonRetraitActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void ButtonListeClient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListeClient1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonListeClient1ActionPerformed

    private void ButtonListeClient2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonListeClient2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonListeClient2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudensBanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudensBanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudensBanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudensBanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudensBanque().setVisible(true);
            
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AButtonDepot;
    private javax.swing.JButton AButtonInfoClient;
    private javax.swing.JButton AButtonInfoCompte;
    private javax.swing.JButton AButtonInfoOperation;
    private javax.swing.JButton AButtonNouveauClient;
    private javax.swing.JButton AButtonNouveauCompte;
    private javax.swing.JButton AButtonRetrait;
    private javax.swing.JButton AButtonSolde;
    private javax.swing.JLabel Accueil1;
    private javax.swing.JLabel Accueil2;
    private javax.swing.JButton ButtonAccueil;
    private javax.swing.JButton ButtonInfCompte;
    private javax.swing.JButton ButtonInfoClient;
    private javax.swing.JButton ButtonListeClient;
    private javax.swing.JButton ButtonListeClient1;
    private javax.swing.JButton ButtonListeClient2;
    private javax.swing.JButton ButtonNouveauClient;
    private javax.swing.JButton ButtonNouveauCompte;
    private javax.swing.JButton Buttonoperation;
    private javax.swing.JPanel PabelAccueill;
    private javax.swing.JPanel PanelNouveauClient;
    private javax.swing.JPanel PanelNouveauCompte;
    private javax.swing.JPanel PannelMain;
    private javax.swing.JPanel PanrlBienvenue;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
